/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_estru_2;

import java.awt.Label;
import java.sql.*;
import java.net.URL;
import java.util.HashSet;
import javax.swing.*;

/**
 *
 * @author bryan
 */
public class Loggin extends javax.swing.JFrame {

    /**
     * Creates new form Loggin
     */
    ConexionMariaDB conexMariaDB = new ConexionMariaDB();
    ConexionSQLServer conexSQLServer = new ConexionSQLServer();
    //Datos MariaDB
    String hostMariaDB = "databasemariadb.c4rmmgpbufto.us-east-1.rds.amazonaws.com";
    String portMariaDB = "3306";
    String dbNameMariaDB = "prueba";
    String userNameMariaDB = "admin";
    String userPassMariaDB = "admin123";
    
    //Datos SQLServer
    String hostSQLServer = "databasesqlserver.c4rmmgpbufto.us-east-1.rds.amazonaws.com";
    String portSQLServer = "1433";
    String dbNameSQLServer = "prueba";
    String userNameSQLServer = "admin";
    String userPassSQLServer = "admin123";
    public Loggin() {
        initComponents();
        this.setResizable(false);
        this.setSize(1153,680);
        this.setLocationRelativeTo(null);
        Fondo5.setVisible(true);
        jPanel5.setVisible(false);
        Menu.setVisible(false);
        Fondo4.setVisible(true);
        Cambio_Ecena_Menu cmm = new Cambio_Ecena_Menu(Fondo4,Fondo5 ,Menu);
        cmm.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Icono_Conectado = new javax.swing.JLabel();
        Icono_replica = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Conexiones = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Nom_Puerto1 = new javax.swing.JTextField();
        Boton_Probar_Coneccion1 = new javax.swing.JButton();
        Nom_Insta_1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        Nom_BaseDato_1 = new javax.swing.JTextField();
        Nom_Usu1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        Nom_Pass_1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Nom_Insta_2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        Nom_BaseDato_2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Nom_Puerto2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        Nom_Usu2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        Nom_Pass_2 = new javax.swing.JTextField();
        Boton_Guardar_db = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_Probar_Coneccion2 = new javax.swing.JButton();
        Panel_Replica = new javax.swing.JPanel();
        Boton_Guardar_Replicas = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla_sin_replicar = new javax.swing.JTable();
        Boton_Cancelar_Replicas = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tabla_replicada = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Flecha_Izquierda = new javax.swing.JLabel();
        Flecha_Derecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Fondo5 = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Menu.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102,150));
        jPanel2.setLayout(null);

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/cerrar-sesion (1).png"))); // NOI18N
        jLabel72.setText("Salir");
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel72);
        jLabel72.setBounds(970, 20, 70, 40);

        Menu.add(jPanel2);
        jPanel2.setBounds(90, 580, 1060, 70);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102,150));
        jPanel4.setLayout(null);

        Icono_Conectado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/conectado_estatico.png"))); // NOI18N
        Icono_Conectado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icono_ConectadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Icono_ConectadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Icono_ConectadoMouseExited(evt);
            }
        });
        jPanel4.add(Icono_Conectado);
        Icono_Conectado.setBounds(10, 10, 80, 80);

        Icono_replica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/entrega-de-correo_estatica.png"))); // NOI18N
        Icono_replica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icono_replicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Icono_replicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Icono_replicaMouseExited(evt);
            }
        });
        jPanel4.add(Icono_replica);
        Icono_replica.setBounds(10, 110, 80, 80);

        Menu.add(jPanel4);
        jPanel4.setBounds(0, 0, 90, 650);

        jPanel5.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/trabajo-en-progreso.png"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(180, 90, 256, 256);

        Menu.add(jPanel5);
        jPanel5.setBounds(300, 120, 600, 420);

        Panel_Conexiones.setBackground(new java.awt.Color(0, 0, 0,150));
        Panel_Conexiones.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.setPreferredSize(new java.awt.Dimension(1070, 610));
        Panel_Conexiones.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(137, 250, 230));
        jLabel23.setText("Nombre Instancia");
        Panel_Conexiones.add(jLabel23);
        jLabel23.setBounds(130, 100, 160, 30);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(137, 250, 230));
        jLabel24.setText("Puerto");
        Panel_Conexiones.add(jLabel24);
        jLabel24.setBounds(130, 240, 130, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(137, 250, 230));
        jLabel25.setText("Base De Datos Destino");
        Panel_Conexiones.add(jLabel25);
        jLabel25.setBounds(710, 20, 260, 30);

        Nom_Puerto1.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Puerto1.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Puerto1);
        Nom_Puerto1.setBounds(130, 270, 210, 30);

        Boton_Probar_Coneccion1.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Probar_Coneccion1.setForeground(new java.awt.Color(0, 0, 0));
        Boton_Probar_Coneccion1.setText("Probar");
        Boton_Probar_Coneccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Probar_Coneccion1MouseClicked(evt);
            }
        });
        Panel_Conexiones.add(Boton_Probar_Coneccion1);
        Boton_Probar_Coneccion1.setBounds(160, 470, 110, 40);

        Nom_Insta_1.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Insta_1.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Insta_1);
        Nom_Insta_1.setBounds(130, 130, 210, 30);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(137, 250, 230));
        jLabel41.setText("Nombre Base Datos");
        Panel_Conexiones.add(jLabel41);
        jLabel41.setBounds(130, 170, 180, 30);

        Nom_BaseDato_1.setBackground(new java.awt.Color(102, 102, 102));
        Nom_BaseDato_1.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_BaseDato_1);
        Nom_BaseDato_1.setBounds(130, 200, 210, 30);

        Nom_Usu1.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Usu1.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Usu1);
        Nom_Usu1.setBounds(130, 340, 210, 30);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(137, 250, 230));
        jLabel42.setText("Nombre Usuario");
        Panel_Conexiones.add(jLabel42);
        jLabel42.setBounds(130, 310, 150, 30);

        Nom_Pass_1.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Pass_1.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Pass_1);
        Nom_Pass_1.setBounds(130, 410, 210, 30);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(137, 250, 230));
        jLabel52.setText("Password");
        Panel_Conexiones.add(jLabel52);
        jLabel52.setBounds(130, 380, 130, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(137, 250, 230));
        jLabel29.setText("Nombre Instancia");
        Panel_Conexiones.add(jLabel29);
        jLabel29.setBounds(730, 100, 160, 30);

        Nom_Insta_2.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Insta_2.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Insta_2);
        Nom_Insta_2.setBounds(730, 130, 210, 30);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(137, 250, 230));
        jLabel43.setText("Nombre Base Datos");
        Panel_Conexiones.add(jLabel43);
        jLabel43.setBounds(730, 170, 180, 30);

        Nom_BaseDato_2.setBackground(new java.awt.Color(102, 102, 102));
        Nom_BaseDato_2.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_BaseDato_2);
        Nom_BaseDato_2.setBounds(730, 200, 210, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(137, 250, 230));
        jLabel30.setText("Puerto");
        Panel_Conexiones.add(jLabel30);
        jLabel30.setBounds(730, 240, 130, 30);

        Nom_Puerto2.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Puerto2.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Puerto2);
        Nom_Puerto2.setBounds(730, 270, 210, 30);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(137, 250, 230));
        jLabel47.setText("Nombre Usuario");
        Panel_Conexiones.add(jLabel47);
        jLabel47.setBounds(730, 310, 150, 30);

        Nom_Usu2.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Usu2.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Usu2);
        Nom_Usu2.setBounds(730, 340, 210, 30);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(137, 250, 230));
        jLabel56.setText("Password");
        Panel_Conexiones.add(jLabel56);
        jLabel56.setBounds(730, 380, 130, 30);

        Nom_Pass_2.setBackground(new java.awt.Color(102, 102, 102));
        Nom_Pass_2.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Conexiones.add(Nom_Pass_2);
        Nom_Pass_2.setBounds(730, 410, 210, 30);

        Boton_Guardar_db.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Guardar_db.setForeground(new java.awt.Color(0, 0, 0));
        Boton_Guardar_db.setText("Guardar");
        Boton_Guardar_db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Guardar_dbMouseClicked(evt);
            }
        });
        Panel_Conexiones.add(Boton_Guardar_db);
        Boton_Guardar_db.setBounds(460, 490, 150, 60);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(137, 250, 230));
        jLabel31.setText("Base De Datos Origen");
        Panel_Conexiones.add(jLabel31);
        jLabel31.setBounds(100, 20, 260, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/mensaje.gif"))); // NOI18N
        jPanel1.add(jLabel1);

        Panel_Conexiones.add(jPanel1);
        jPanel1.setBounds(420, 160, 230, 240);

        Boton_Probar_Coneccion2.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Probar_Coneccion2.setForeground(new java.awt.Color(0, 0, 0));
        Boton_Probar_Coneccion2.setText("Probar");
        Boton_Probar_Coneccion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Probar_Coneccion2MouseClicked(evt);
            }
        });
        Panel_Conexiones.add(Boton_Probar_Coneccion2);
        Boton_Probar_Coneccion2.setBounds(760, 470, 110, 40);

        Menu.add(Panel_Conexiones);
        Panel_Conexiones.setBounds(1230, 0, 1080, 580);

        Panel_Replica.setBackground(new java.awt.Color(0, 0, 0,150));
        Panel_Replica.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Replica.setPreferredSize(new java.awt.Dimension(1070, 610));
        Panel_Replica.setLayout(null);

        Boton_Guardar_Replicas.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Guardar_Replicas.setForeground(new java.awt.Color(0, 0, 0));
        Boton_Guardar_Replicas.setText("Guardar");
        Boton_Guardar_Replicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Guardar_ReplicasMouseClicked(evt);
            }
        });
        Panel_Replica.add(Boton_Guardar_Replicas);
        Boton_Guardar_Replicas.setBounds(370, 490, 110, 40);

        Tabla_sin_replicar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(Tabla_sin_replicar);

        Panel_Replica.add(jScrollPane5);
        jScrollPane5.setBounds(20, 80, 310, 450);

        Boton_Cancelar_Replicas.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Cancelar_Replicas.setForeground(new java.awt.Color(0, 0, 0));
        Boton_Cancelar_Replicas.setText("Cancelar");
        Boton_Cancelar_Replicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Cancelar_ReplicasMouseClicked(evt);
            }
        });
        Panel_Replica.add(Boton_Cancelar_Replicas);
        Boton_Cancelar_Replicas.setBounds(530, 490, 110, 40);

        jScrollPane6.setViewportView(Tabla_replicada);

        Panel_Replica.add(jScrollPane6);
        jScrollPane6.setBounds(690, 80, 310, 450);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(137, 250, 230));
        jLabel32.setText("Replicando");
        Panel_Replica.add(jLabel32);
        jLabel32.setBounds(770, 20, 150, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(137, 250, 230));
        jLabel33.setText("Sin Replicar");
        Panel_Replica.add(jLabel33);
        jLabel33.setBounds(90, 20, 150, 30);

        Flecha_Izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Flecha estatica.png"))); // NOI18N
        Flecha_Izquierda.setText("jLabel6");
        Flecha_Izquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Flecha_IzquierdaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Flecha_IzquierdaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Flecha_IzquierdaMouseExited(evt);
            }
        });
        Panel_Replica.add(Flecha_Izquierda);
        Flecha_Izquierda.setBounds(440, 310, 110, 110);

        Flecha_Derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/flecah1 estatico.png"))); // NOI18N
        Flecha_Derecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Flecha_DerechaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Flecha_DerechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Flecha_DerechaMouseExited(evt);
            }
        });
        Panel_Replica.add(Flecha_Derecha);
        Flecha_Derecha.setBounds(440, 150, 110, 110);

        Menu.add(Panel_Replica);
        Panel_Replica.setBounds(1230, 0, 1060, 580);

        jPanel3.setBackground(new java.awt.Color(225, 225, 225,151));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        Menu.add(jPanel3);
        jPanel3.setBounds(90, 0, 1060, 580);

        Fondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/frame menu.png"))); // NOI18N
        Menu.add(Fondo5);
        Fondo5.setBounds(0, 0, 1152, 650);

        getContentPane().add(Menu);
        Menu.setBounds(0, 0, 2370, 650);

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/continuacion-animacion_1.gif"))); // NOI18N
        getContentPane().add(Fondo4);
        Fondo4.setBounds(-3, -4, 1160, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Probar_Coneccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Probar_Coneccion1MouseClicked
        conexMariaDB.setHost(Nom_Insta_1.getText());
        conexMariaDB.setdbName(Nom_BaseDato_1.getText());
        conexMariaDB.setPort(Nom_Puerto1.getText());
        conexMariaDB.setUser(Nom_Usu1.getText());
        conexMariaDB.setPass(Nom_Pass_1.getText());
        //este metodo hace que se vea la imagen de work
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                conexMariaDB.conectarMariaDB();
                if(conexMariaDB.getConectado() == true){
                    JOptionPane.showMessageDialog(null, "Conectado Exitosamente a MariaDB");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Conexion Fallida a MariaDB");
                }
                //aqui pones las lineas de la db para que aparezca la imagen 
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina
    }//GEN-LAST:event_Boton_Probar_Coneccion1MouseClicked

    private void Boton_Guardar_ReplicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Guardar_ReplicasMouseClicked
        //este metodo hace que se vea la imagen de work
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //aqui pones las lineas de la db para que aparezca la imagen 
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina

    }//GEN-LAST:event_Boton_Guardar_ReplicasMouseClicked

    private void Boton_Guardar_dbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Guardar_dbMouseClicked
        //este metodo hace que se vea la imagen de work
        conexMariaDB.setHost(Nom_Insta_1.getText());
        conexMariaDB.setdbName(Nom_BaseDato_1.getText());
        conexMariaDB.setPort(Nom_Puerto1.getText());
        conexMariaDB.setUser(Nom_Usu1.getText());
        conexMariaDB.setPass(Nom_Pass_1.getText());

        conexSQLServer.setHost(Nom_Insta_2.getText());
        conexSQLServer.setdbName(Nom_BaseDato_2.getText());
        conexSQLServer.setPort(Nom_Puerto2.getText());
        conexSQLServer.setUser(Nom_Usu2.getText());
        conexSQLServer.setPass(Nom_Pass_2.getText());
        
        hostMariaDB = Nom_Insta_1.getText();
        dbNameMariaDB = Nom_BaseDato_1.getText();
        portMariaDB = Nom_Puerto1.getText();
        userNameMariaDB = Nom_Usu1.getText();
        userPassMariaDB = Nom_Pass_1.getText();
        
        hostSQLServer = Nom_Insta_2.getText();
        dbNameSQLServer = Nom_BaseDato_2.getText();
        portSQLServer = Nom_Puerto2.getText();
        userNameSQLServer = Nom_Usu2.getText();
        userPassSQLServer = Nom_Pass_2.getText();
        
                
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //aqui pones las lineas de la db para que aparezca la imagen 
                
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina
    }//GEN-LAST:event_Boton_Guardar_dbMouseClicked

    private void Boton_Probar_Coneccion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Probar_Coneccion2MouseClicked
        conexSQLServer.setHost(Nom_Insta_2.getText());
        conexSQLServer.setdbName(Nom_BaseDato_2.getText());
        conexSQLServer.setPort(Nom_Puerto2.getText());
        conexSQLServer.setUser(Nom_Usu2.getText());
        conexSQLServer.setPass(Nom_Pass_2.getText());        
        //este metodo hace que se vea la imagen de work
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                conexSQLServer.conectarSQLServer();
                if(conexSQLServer.getConectado() == true){
                    JOptionPane.showMessageDialog(null, "Conectado Exitosamente a SQLServer");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Conexion Fallida a SQLServer");
                }
                //aqui pones las lineas de la db para que aparezca la imagen 
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina
    }//GEN-LAST:event_Boton_Probar_Coneccion2MouseClicked

    private void Boton_Cancelar_ReplicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Cancelar_ReplicasMouseClicked
        //este metodo hace que se vea la imagen de work
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //aqui pones las lineas de la db para que aparezca la imagen 
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina
    }//GEN-LAST:event_Boton_Cancelar_ReplicasMouseClicked

    private void Icono_ConectadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icono_ConectadoMouseEntered
        String rutaImagen = "/Media/conectado.gif";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Icono_Conectado.setIcon(icono);
        establecerDatosMariaDB();
        establecerDatosSQLServer();
    }//GEN-LAST:event_Icono_ConectadoMouseEntered

    private void Icono_ConectadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icono_ConectadoMouseExited
        String rutaImagen = "/Media/conectado_estatico.png";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Icono_Conectado.setIcon(icono);
    }//GEN-LAST:event_Icono_ConectadoMouseExited

    private void Icono_replicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icono_replicaMouseEntered
        String rutaImagen = "/Media/entrega-de-correo.gif";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Icono_replica.setIcon(icono);
    }//GEN-LAST:event_Icono_replicaMouseEntered

    private void Icono_replicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icono_replicaMouseExited
        String rutaImagen = "/Media/entrega-de-correo_estatica.png";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Icono_replica.setIcon(icono);
    }//GEN-LAST:event_Icono_replicaMouseExited

    private void Icono_replicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icono_replicaMouseClicked
        if(conexMariaDB.getConectado() == true && conexSQLServer.getConectado() == true){
            Cambio_Menu CM= new Cambio_Menu(Panel_Replica,Panel_Conexiones);
            CM.start();
            try{
                Statement st = conexMariaDB.conexion.createStatement();
                String qt = "CALL CrearTriggerParaTablas();";
                st.executeUpdate(qt);
                st.close();
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe Establecer Conexiones Primero");
        }
    }//GEN-LAST:event_Icono_replicaMouseClicked

    private void Icono_ConectadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icono_ConectadoMouseClicked
        Cambio_Menu CM= new Cambio_Menu(Panel_Conexiones,Panel_Replica);
        CM.start();
    }//GEN-LAST:event_Icono_ConectadoMouseClicked

    private void Flecha_DerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_DerechaMouseClicked
        //este metodo hace que se vea la imagen de work
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //aqui pones las lineas de la db para que aparezca la imagen 
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina
    }//GEN-LAST:event_Flecha_DerechaMouseClicked

    private void Flecha_DerechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_DerechaMouseEntered
        String rutaImagen = "/Media/flechas1.gif";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Flecha_Derecha.setIcon(icono);
    }//GEN-LAST:event_Flecha_DerechaMouseEntered

    private void Flecha_DerechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_DerechaMouseExited
        String rutaImagen = "/Media/flecah1 estatico.png";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Flecha_Derecha.setIcon(icono);
    }//GEN-LAST:event_Flecha_DerechaMouseExited

    private void Flecha_IzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_IzquierdaMouseClicked
       //este metodo hace que se vea la imagen de work
        jPanel5.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //aqui pones las lineas de la db para que aparezca la imagen 
                jPanel5.setVisible(false);
            }
        });
        //aaqui termina
    }//GEN-LAST:event_Flecha_IzquierdaMouseClicked

    private void Flecha_IzquierdaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_IzquierdaMouseEntered
        String rutaImagen = "/Media/flechas-(1).gif";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Flecha_Izquierda.setIcon(icono);
    }//GEN-LAST:event_Flecha_IzquierdaMouseEntered

    private void Flecha_IzquierdaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_IzquierdaMouseExited
        String rutaImagen = "/Media/Flecha estatica.png";
        URL urlImagen = getClass().getResource(rutaImagen);
        ImageIcon icono = new ImageIcon(urlImagen);
        Flecha_Izquierda.setIcon(icono);
    }//GEN-LAST:event_Flecha_IzquierdaMouseExited

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        if(conexMariaDB.getConectado() == true){
            conexMariaDB.desconectar();
        }
        if(conexSQLServer.getConectado() == true){
            conexSQLServer.desconectar();
        }
        System.exit(0);
        
    }//GEN-LAST:event_jLabel72MouseClicked
    private void establecerDatosMariaDB(){
        //Base de Datos Origen
        Nom_Insta_1.setText(hostMariaDB);
        Nom_BaseDato_1.setText(dbNameMariaDB);
        Nom_Puerto1.setText(portMariaDB);
        Nom_Usu1.setText(userNameMariaDB);
        Nom_Pass_1.setText(userPassMariaDB);
    }
    private void establecerDatosSQLServer(){
        //Base de Datos Origen
        Nom_Insta_2.setText(hostSQLServer);
        Nom_BaseDato_2.setText(dbNameSQLServer);
        Nom_Puerto2.setText(portSQLServer);
        Nom_Usu2.setText(userNameSQLServer);
        Nom_Pass_2.setText(userPassSQLServer);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Cancelar_Replicas;
    private javax.swing.JButton Boton_Guardar_Replicas;
    private javax.swing.JButton Boton_Guardar_db;
    private javax.swing.JButton Boton_Probar_Coneccion1;
    private javax.swing.JButton Boton_Probar_Coneccion2;
    private javax.swing.JLabel Flecha_Derecha;
    private javax.swing.JLabel Flecha_Izquierda;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JLabel Fondo5;
    private javax.swing.JLabel Icono_Conectado;
    private javax.swing.JLabel Icono_replica;
    private javax.swing.JPanel Menu;
    private javax.swing.JTextField Nom_BaseDato_1;
    private javax.swing.JTextField Nom_BaseDato_2;
    private javax.swing.JTextField Nom_Insta_1;
    private javax.swing.JTextField Nom_Insta_2;
    private javax.swing.JTextField Nom_Pass_1;
    private javax.swing.JTextField Nom_Pass_2;
    private javax.swing.JTextField Nom_Puerto1;
    private javax.swing.JTextField Nom_Puerto2;
    private javax.swing.JTextField Nom_Usu1;
    private javax.swing.JTextField Nom_Usu2;
    private javax.swing.JPanel Panel_Conexiones;
    private javax.swing.JPanel Panel_Replica;
    private javax.swing.JTable Tabla_replicada;
    private javax.swing.JTable Tabla_sin_replicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
